name: dloader
description: 'A simple and versatile library for downloading files with support for adapters including dio, curl, wget, powershell, aria2 and axel. Feel free to create new adapters.'
version: 1.2.9
repository: https://github.com/insign/dart_dloader
homepage: https://github.com/insign/dart_dloader

environment:
  sdk: '>=3.9.4 <4.0.0'

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3

dependencies:
  dio: ^5.9.0
  executable: ^1.4.1
  path: ^1.9.1
